// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITpCQLmwpIGp1U6CCmpBXbjdoqDNueas',
    appId: '1:570501809233:android:bd9de0c8d59e84cc5ee470',
    messagingSenderId: '570501809233',
    projectId: 'testing-cli2-5a3ac',
    databaseURL: 'https://testing-cli2-5a3ac-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli2-5a3ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdrdhdJDDNw1mWSgDPLZ0K5FIXlTxbdVA',
    appId: '1:570501809233:ios:9cbeccadbf446f715ee470',
    messagingSenderId: '570501809233',
    projectId: 'testing-cli2-5a3ac',
    databaseURL: 'https://testing-cli2-5a3ac-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli2-5a3ac.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
